### ISSUE TITLE
Time entry no /disable AM PM

### ISSUE THREAD

**Issue by weedkiller** [gregersrygg/jquery.timeInput#3]
Hi, I have user who just want to **enter amount of time worked only, i.e. no AM or PM**, i.e. how long and _not_ when for 8HRs, or 14 hrs etc.

I was unable to disable the AM & PM text, can you please share the setting/example to disable it.

Also 

- [ ] SHow only time entry, not AM/PM or dates
- [ ] how to show default hours: for e.g. on select box, `default to 08:00 hrs.` no AM or PM
- [ ] Different color for HH:MM hours (Blue) and Mins (green)
- [ ] show a button to fill `https://github.com/kbwood/timeentry/blob/master/jquery.timeentry.js`
![image](https://user-images.githubusercontent.com/21086190/34395645-00141932-eb30-11e7-9288-dc1586832120.png)

thanks

**Comment by gregersrygg** [comment]
Sorry, this library is not maintained anymore.
